name: publish-package
run-name: ${{ github.actor }} is publishing package

on:
  pull_request:
    branches: [master]
    types:
      - closed
    paths:
      - 'package.json'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM }}
